import "./globals.css";

export const metadata = {
  title: "Technology Transferred Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased font-geist"
        data-new-gr-c-s-check-loaded="14.1100.0"
        data-gr-ext-installed=""

      >
        {children}
      </body>
    </html>
  );
}
